Switch to version catalog for dependencies
refinedmods/refinedstorage2 pull request #253
Opened 2022-12-27 21:16 UTC by bulldog98

This PR changes the build according to #234

2022-12-28 20:09 UTC, raoulvdberge requested changes

2022-12-28 20:09 UTC, raoulvdberge commented on gradle.properties
>  parchmentVersion=2022.08.21
Can these be removed now somehow?

2022-12-28 20:09 UTC, raoulvdberge commented on refinedstorage2-core-api/build.gradle
> +    testImplementation testLibs.bundles.junit
I'm not really a fan of using bundles for junit. The engine should only be provided at runtime, not in implementation.

2022-12-29 09:14 UTC, bulldog98 commented on gradle.properties
>  parchmentVersion=2022.08.21
At the moment I was not able to configure the parchment version via version catalog, opened a bug in the fabric loom gradle plugin about that https://github.com/FabricMC/fabric-loom/issues/782

2022-12-29 09:15 UTC, bulldog98 commented on refinedstorage2-core-api/build.gradle
> +    testImplementation testLibs.bundles.junit
Will fix that today or tomorrow.

2022-12-29 09:46 UTC, raoulvdberge commented on gradle.properties
>  parchmentVersion=2022.08.21
In that case, maybe put a TODO comment on there with a link to your issue.

2022-12-29 17:35 UTC, bulldog98 commented on gradle.properties
>  parchmentVersion=2022.08.21
I had a thought, how to get rid of the versions there, you can also only define a version in the catalog and use it in a string interpolation, we should still add that TODO with the link. Not sure if it should be at the position where the version is defined, or at the position where it's used.

2022-12-29 17:47 UTC, raoulvdberge commented on gradle.properties
>  parchmentVersion=2022.08.21
That's even better. Probably in the position where it's used,  I think..?

2022-12-29 19:42 UTC, raoulvdberge commented
Can you also rebase? I did a minor change to the checkstyle config on develop.

2022-12-30 16:37 UTC, bulldog98 commented on refinedstorage2-core-api/build.gradle
> +    testImplementation testLibs.bundles.junit
Done

2022-12-30 16:38 UTC, bulldog98 commented on gradle.properties
>  parchmentVersion=2022.08.21
Could you check if that is ok like that?

2022-12-30 17:02 UTC, raoulvdberge commented
The build is failing. `refinedstorage2-network-test` needs to have Junit on the implementation scope.

2022-12-30 17:10 UTC, bulldog98 commented
> The build is failing. `refinedstorage2-network-test` needs to have Junit on the implementation scope.
Fixed that

2022-12-30 20:23 UTC, raoulvdberge requested changes
Almost there. Just a small question and request.

2022-12-30 20:23 UTC, raoulvdberge commented on gradlew
> +#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
Could you undo changes in this file?

2022-12-30 20:23 UTC, raoulvdberge commented on refinedstorage2-platform-forge/build.gradle
> -        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
Why did you remove this?

2022-12-30 20:23 UTC, raoulvdberge commented on refinedstorage2-platform-forge/build.gradle
> -apply plugin: 'net.minecraftforge.gradle'
Why did you remove this?

2022-12-30 21:31 UTC, bulldog98 commented on refinedstorage2-platform-forge/build.gradle
> -        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
Ah that was the old way to apply gradle plugins, that is the legacy way to add a plugin see https://docs.gradle.org/current/userguide/plugins.html#sec:old_plugin_application

2022-12-30 21:32 UTC, bulldog98 commented on refinedstorage2-platform-forge/build.gradle
> +    alias(forge.plugins.forgeGradle)
This is the modern and recommended way to use a plugin

2022-12-30 21:33 UTC, raoulvdberge commented on refinedstorage2-platform-forge/build.gradle
> +    alias(forge.plugins.forgeGradle)
cool, thanks!

2022-12-31 09:08 UTC, raoulvdberge commented on gradlew
> +#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
Heh. Looks like github was just rendering it weirdly.
![image](https://user-images.githubusercontent.com/10358424/210131385-24f53952-6f5c-47d6-b7db-0f3f2b0bb43c.png)

Checked the branch out and looks fine locally.

2022-12-31 09:08 UTC, raoulvdberge approved these changes

2022-12-31 09:08 UTC, raoulvdberge commented
Thanks!

2022-12-31 09:08 UTC, merged