Implement JEI under mouse api
refinedmods/refinedstorage2 pull request #261
Opened 2023-01-02 12:49 UTC by bulldog98

This implements a part of #208

2023-01-02 17:02 UTC, raoulvdberge requested changes
It seems like you forgot to remove the JeiGridSynchronizer/JeiPlugin/JeiProxy classes from the Forge module?

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiFilterContainerHandler.java
> +        if (filteredResource.getValue() instanceof ItemResource itemResource) {
This logic needs to be moved to a registry in `PlatformApi`. If you do it like this, addons can't add their own JEI mapping.

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiFilterContainerHandler.java
> +    public @Nullable Object handleFilteredResource(final FilteredResource filteredResource) {
`@Nullable` annotation must be before `public` on a separate line

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiPlugin.java
> +            this.toCall.add((fluidHelper) -> {
This is not really clean. Can't we just retrieve the fluid helper at runtime from the runtime variable instead of injecting it?

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiGridHandler.java
> +public class JeiGridHandler implements
Bad naming: `GridGuiContainerHandler`

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiFilterContainerHandler.java
> +public class JeiFilterContainerHandler
Bad naming: `FilterGuiContainerHandler`

2023-01-02 17:02 UTC, raoulvdberge commented on CHANGELOG.md
> +- Jei under mouse support in Grids, Exporter, Importer and ExternalStorage
```suggestion
- Support for using the R/U keys in JEI on Grid slots and filtering slots
```

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiFilterContainerHandler.java
> +            final double mouseX, final double mouseY
`mouseY` must be newline

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiGridHandler.java
> +        final var resource = containerScreen.getMenu().getView().getAll().get(slot);
This has too many indirections. The GUI should probably be responsible for returning the resource. Just returning the grid slot number from there is too low level.

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiPlugin.java
> +public class JeiPlugin implements IModPlugin {
Bad naming: `RefinedStorageModPlugin`

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/screen/AbstractBaseScreen.java
> +    public @Nullable Slot getHoveredSlot() {
Nullable is on the wrong line.

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/screen/grid/AbstractGridScreen.java
> +        return this.gridSlotNumber;
This is too low level. Just return the resource from here.

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-fabric/build.gradle
> +    modImplementation fabric.bundles.jei
Please don't use bundles for JEI/REI. It's too confusing.

2023-01-02 17:02 UTC, raoulvdberge commented on refinedstorage2-platform-forge/build.gradle
> +    implementation fg.deobf(forge.jei.common.api.get())
Why?

2023-01-02 17:06 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiPlugin.java
> +            this.toCall.add((fluidHelper) -> {
Sadly no, because the `onRuntimeAvailable` is called after `registerGuiHandlers`, so we have to work around that.

2023-01-02 17:09 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiPlugin.java
> +            this.toCall.add((fluidHelper) -> {
That doesn't matter, you can use `JeiPlugin.getRuntime().getJeiHelpers().getPlatformFluidHelper()` in the `getIngredientUnderMouse` method, I think?

2023-01-02 17:16 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiPlugin.java
> +            this.toCall.add((fluidHelper) -> {
Will try that.

2023-01-02 17:23 UTC, bulldog98 commented on refinedstorage2-platform-fabric/build.gradle
> +    modImplementation fabric.bundles.jei
alright I'll slit it up.

2023-01-02 17:29 UTC, bulldog98 commented on refinedstorage2-platform-forge/build.gradle
> +    implementation fg.deobf(forge.jei.common.api.get())
Indeed not needed, will take that back

2023-01-02 18:30 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/JeiPlugin.java
> +            this.toCall.add((fluidHelper) -> {
does not work that way, but with the converter idea we got around that.

2023-01-02 19:41 UTC, raoulvdberge requested changes

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-api/src/main/java/com/refinedmods/refinedstorage2/platform/api/PlatformApi.java
> +    @API(status = API.Status.STABLE, since = "2.0.0-milestone.2.5")
We don't really put API annotations on individual method (too much work to maintain), just on class level. So I think you can remove these.

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/PlatformApiImpl.java
> +        this.converters.add(converter);
Please write a `CompositeIngredientConverter` and keep the converters in that object

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/PlatformApiImpl.java
> +        return new IngredientConverter() {
Don't create a new instance everytime, use `CompositeIngredientConverter`

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/PlatformApiImpl.java
> +                        .flatMap((conv) -> conv.convertToIngredient(resource).stream())
unneeded parenthesis (conv)

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/PlatformApiImpl.java
> +                        .flatMap((conv) -> conv.convertToIngredient(ingredient).stream())
unneeded parenthesis (conv)

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-api/src/main/java/com/refinedmods/refinedstorage2/platform/api/resource/IngredientConverter.java
> +package com.refinedmods.refinedstorage2.platform.api.resource;
I think this class must be part of an integration pkg instead of core resource package.

Maybe: `com.refinedmods.refinedstorage2.platform.api.integration.recipemod`?

The impls can go in `com.refinedmods.refinedstorage2.platform.common.integration.recipemod.jei`.

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/FilterGuiContainerHandler.java
> +        IngredientConverter converter
I don't think the code has 8 spaces anywhere.

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/FilterGuiContainerHandler.java
> +            final var filteredResource = slot.getFilteredResource();
We don't really use var anywhere.

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/FilterGuiContainerHandler.java
> +            final AbstractBaseScreen<? extends AbstractResourceFilterContainerMenu> containerScreen,
8 spaces issue

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/FilterIngredientConverter.java
> +public record FilterIngredientConverter(IPlatformFluidHelper<?> fluidHelper) implements IngredientConverter {
Why is this a record? FluidHelper doesn't need to be public.

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/GridGuiContainerHandler.java
> +        IngredientConverter converter
No need for a record. converter doesn't need to be public.

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/GridGuiContainerHandler.java
> +        return converter.convertToResource(resource).orElse(null);
Doesn't this need to be `convertToIngredient` ?

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/RefinedStorageModPlugin.java
> +            final var fluidHelper = newRuntime.getJeiHelpers().getPlatformFluidHelper();
No var

2023-01-02 19:41 UTC, raoulvdberge commented on refinedstorage2-platform-fabric/build.gradle
> +    modImplementation fabric.jei.common.api
`modCompileOnly`

2023-01-02 20:52 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/PlatformApiImpl.java
> +        this.converters.add(converter);
do you want in common makes the most sense I suppose

2023-01-02 20:57 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/FilterIngredientConverter.java
> +public record FilterIngredientConverter(IPlatformFluidHelper<?> fluidHelper) implements IngredientConverter {
intellij suggested it.

2023-01-02 21:00 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/GridGuiContainerHandler.java
> +        return converter.convertToResource(resource).orElse(null);
yeah switched that around in both handlers and in the converter implementation.

2023-01-02 21:00 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/integration/jei/GridGuiContainerHandler.java
> +        IngredientConverter converter
same here intellij suggested it.

2023-01-13 18:27 UTC, bulldog98 commented
To comply with the new branch name requirement I open a new PR

2023-01-13 18:27 UTC, closed without merging