feat: implement different cable colors
refinedmods/refinedstorage2 pull request #317
Opened 2023-02-06 20:10 UTC by bulldog98

implements #172

This Pr superseeds #267

2023-02-06 20:10 UTC, bulldog98 commented
How do we attribute the art?

2023-02-07 15:30 UTC, raoulvdberge requested changes
We now have `grey_cable.png` and  `cable.png`, we only need 1.

2023-02-07 15:30 UTC, raoulvdberge commented on CHANGELOG.md
> +- Support for different colors of cable, that only connect to same colored cable and other RS parts
```suggestion
- Different Cable colors. They only connect to same colored cables or the default cable.
```

2023-02-07 15:30 UTC, raoulvdberge commented on refinedstorage2-platform-api/src/main/java/com/refinedmods/refinedstorage2/platform/api/network/node/PlatformNetworkNodeContainer.java
> +    default boolean canConnectTo(PlatformNetworkNodeContainer other) {
Can this be combined in `canAcceptIncomingConnection` ? If you pass the `other` there.

2023-02-07 15:30 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/generated/resources/assets/refinedstorage2/models/block/cable/cable_core.json
> +    "cable": "refinedstorage2:block/cable/cable",
I think the model file naming is inconsistent here. For example, blockstate `grid.json` refers to `block/grid/light_blue`.

So I'd expect that this file is named `block/cable/core/gray.json`. Same for the texture filename.

2023-02-07 15:30 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/generated/resources/assets/refinedstorage2/models/block/cable/cable_extension.json
> +    "cable": "refinedstorage2:block/cable/cable",
I think the model file naming is inconsistent here. For example, blockstate `grid.json` refers to `block/grid/light_blue`.

So I'd expect that this file is named `block/cable/extension/gray.json`. Same for the texture filename.

2023-02-07 15:30 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +    private static final ColorMap<AbstractBlockEntityTicker<CableBlockEntity>> TICKER = new ColorMap<>();
Just instantiate the ticker in the constructor. No need for a static map

2023-02-07 15:30 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/entity/CableBlockEntity.java
> +            return this.color == otherCable.color && super.canConnectTo(other);
Sorry, I changed my mind about this. Can we *do* connect to the default color in all cases?

2023-02-07 15:30 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/content/ColorMap.java
> +    public ResourceLocation getId(final DyeColor color, final DyeColor defaultColor, final ResourceLocation id) {
I'd make the default color be a property of `ColorMap`. And default it to `NORMAL_COLOR`

2023-02-07 15:32 UTC, raoulvdberge commented
No need to attribute the art. Cyanide is the artist and he's attributed on the Curseforge page.

2023-02-08 18:09 UTC, bulldog98 commented on refinedstorage2-platform-common/src/generated/resources/assets/refinedstorage2/models/block/cable/cable_extension.json
> +    "cable": "refinedstorage2:block/cable/cable",
Do you want the default cable to be light_blue? I thought it looks like it's gray, so I made that the default color for cables (Cable being Gray Cable). Need clarification on that one.

2023-02-08 18:25 UTC, bulldog98 commented on refinedstorage2-platform-common/src/generated/resources/assets/refinedstorage2/models/block/cable/cable_extension.json
> +    "cable": "refinedstorage2:block/cable/cable",
Also the particle is needed, otherwise you will get particle without texture on breaking the cables

2023-02-08 19:17 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/generated/resources/assets/refinedstorage2/models/block/cable/cable_extension.json
> +    "cable": "refinedstorage2:block/cable/cable",
No that was just an example. Default color for cables is grey.

2023-02-08 19:18 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/generated/resources/assets/refinedstorage2/models/block/cable/cable_extension.json
> +    "cable": "refinedstorage2:block/cable/cable",
This comment is about renaming the default cable model to grey.json

2023-02-08 19:19 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/generated/resources/assets/refinedstorage2/models/block/cable/cable_extension.json
> +    "cable": "refinedstorage2:block/cable/cable",
Maybe look how the grid structure is. Same thing, but default is grey

2023-02-09 18:31 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +    private static final ColorMap<AbstractBlockEntityTicker<CableBlockEntity>> TICKER = new ColorMap<>();
I'm not sure, if what I did change is what you ment.

2023-02-11 15:09 UTC, raoulvdberge requested changes
Can you make it so that there is a common model for following models:

- Core
- Extension
- Item model

The elements are duplicated *everywhere* atm.

You'd get something like this, for core:

`models/block/cable/core/black.json`:
```json 
{
  "parent": "refinedstorage2:block/cable/core/base",
  "textures": {
    "cable": "refinedstorage2:block/cable/black",
    "particle": "refinedstorage2:block/cable/black"
  }
}
``` 

`models/block/cable/core/base.json`:
```
{
  "render_type": "cutout",
  "elements": [
    {
      "name": "Core",
      "from": [
        6.0,
        6.0,
        6.0
      ],
      "to": [
        10.0,
        10.0,
        10.0
      ],
      "faces": {
        "north": {
          "texture": "#cable",
          "uv": [
            6.0,
            6.0,
            10.0,
            10.0
          ]
        },
        "east": {
          "texture": "#cable",
          "uv": [
            6.0,
            6.0,
            10.0,
            10.0
          ]
        },
        "south": {
          "texture": "#cable",
          "uv": [
            6.0,
            6.0,
            10.0,
            10.0
          ]
        },
        "west": {
          "texture": "#cable",
          "uv": [
            6.0,
            6.0,
            10.0,
            10.0
          ]
        },
        "up": {
          "texture": "#cable",
          "uv": [
            6.0,
            6.0,
            10.0,
            10.0
          ]
        },
        "down": {
          "texture": "#cable",
          "uv": [
            6.0,
            6.0,
            10.0,
            10.0
          ]
        }
      }
    }
  ]
}
```

This would remove a lot of duplication, even if they are generated files.

We can do the same for the item models & extensions.

(Also don't datagen the base models)

2023-02-11 15:11 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/content/BlockColorMap.java
> +        this(DyeColor.LIGHT_BLUE);
Use `ColorMap.NORMAL_COLOR ` or remove it altogether

2023-02-11 15:11 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +            new NetworkNodeBlockEntityTicker<>(() -> BlockEntities.INSTANCE.getCable().get(DyeColor.GRAY));
Not what I meant. TICKER doesn't need to be static. Just make it a regular attribute of CableBlock and instantiate it in the constructor, you have the color there...

2023-02-11 15:12 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +    private static final ColorMap<AbstractBlockEntityTicker<CableBlockEntity>> TICKER = new ColorMap<>();
Not what I meant, check my other comment.

2023-02-11 15:36 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +            new NetworkNodeBlockEntityTicker<>(() -> BlockEntities.INSTANCE.getCable().get(DyeColor.GRAY));
Does that not mean we have an aditional object per cable around?

2023-02-11 15:48 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +            new NetworkNodeBlockEntityTicker<>(() -> BlockEntities.INSTANCE.getCable().get(DyeColor.GRAY));
Yes, an additional ticker per cable

2023-02-11 15:50 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +            new NetworkNodeBlockEntityTicker<>(() -> BlockEntities.INSTANCE.getCable().get(DyeColor.GRAY));
Wait, why did you create a block entity type per color? I think we can have a single cable block entity type. If we have that, you can have a single ticker.

2023-02-11 15:51 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +            new NetworkNodeBlockEntityTicker<>(() -> BlockEntities.INSTANCE.getCable().get(DyeColor.GRAY));
(multiple blocks can map to the same block entity type)

2023-02-11 15:51 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +            new NetworkNodeBlockEntityTicker<>(() -> BlockEntities.INSTANCE.getCable().get(DyeColor.GRAY));
(and the color is stored in the blockstate anyway.)

2023-02-11 15:54 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +            new NetworkNodeBlockEntityTicker<>(() -> BlockEntities.INSTANCE.getCable().get(DyeColor.GRAY));
Ah, then me creating it was because I'm not to familiar with how minecraft modding works, I'll fix the issue you mentioned.

2023-02-11 17:04 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +            new NetworkNodeBlockEntityTicker<>(() -> BlockEntities.INSTANCE.getCable().get(DyeColor.GRAY));
Not sure if now the logic for the color connection is ok, or not (not sure if getBlockState().getBlock() is expensive)

2023-02-11 18:57 UTC, raoulvdberge requested changes

2023-02-11 18:57 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/ModInitializer.java
> +                CABLE.getPath(),
Remove the 8 space indentations in this file

2023-02-11 18:57 UTC, raoulvdberge commented on refinedstorage2-platform-fabric/src/main/java/com/refinedmods/refinedstorage2/platform/fabric/ModInitializerImpl.java
> +            new CableBlock(color, Blocks.INSTANCE.getCable().getName(
Remove the 8 space indentations in this file

2023-02-11 18:57 UTC, raoulvdberge commented on refinedstorage2-platform-fabric/src/main/java/com/refinedmods/refinedstorage2/platform/fabric/ClientModInitializerImpl.java
> +            ColorMap.generateId(color, DyeColor.LIGHT_BLUE, IdentifierUtil.MOD_ID, "controller"),
Why not use the constant here?

2023-02-11 18:57 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/entity/CableBlockEntity.java
> +        return ((CableBlock) this.getBlockState().getBlock()).getColor();
Unsafe cast; please check if block is instance of CableBlock first. Otherwise return the default color.

2023-02-11 18:57 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +            new NetworkNodeBlockEntityTicker<>(() -> BlockEntities.INSTANCE.getCable().get(DyeColor.GRAY));
getBlockState() should be cached. So I think it's fine

2023-02-11 20:53 UTC, raoulvdberge submitted a review, later dismissed

2023-02-11 21:55 UTC, merged