refactor: rewrite the datagen in java
refinedmods/refinedstorage2 pull request #324
Opened 2023-02-12 20:58 UTC by bulldog98

refactor: #319

2023-02-12 20:58 UTC, bulldog98 commented
do we need a changelog for this?

2023-02-19 09:10 UTC, raoulvdberge requested changes

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-common/datagen/README.md
You can just remove this file.

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/generated/resources/data/refinedstorage2/advancements/recipes/misc/coloring/black_cable.json
> +  "parent": "minecraft:recipes/root",
I don't understand why we suddenly datagen advancements?

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/generated/resources/data/refinedstorage2/tags/items/fluid_storage_disks.json
> +    "refinedstorage2:64b_fluid_storage_part",
This is wrong.

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/generated/resources/data/refinedstorage2/tags/items/storage_disks.json
> -    "refinedstorage2:64k_storage_disk"
This is wrong.

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/BlockStateProvider.java
> +    private final ExistingFileHelper exFileHelper;
```suggestion
    private final ExistingFileHelper existingFileHelper;
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlock.java
> +    );
Just use `Map.of`

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/BlockStateProvider.java
> +            CableBlock.PROPERTY_BY_DIRECTION.forEach((key, value) -> {
```suggestion
            CableBlock.PROPERTY_BY_DIRECTION.forEach((direction, property) -> {
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/BlockStateProvider.java
> +        final ModelFile nearly_on = modelFile(createIdentifier("block/controller/nearly_on"));
```suggestion
        final ModelFile nearlyOff = modelFile(createIdentifier("block/controller/nearly_off"));
        final ModelFile nearlyOn = modelFile(createIdentifier("block/controller/nearly_on"));
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/BlockStateProvider.java
> +        builder.forAllStates((blockState -> {
```suggestion
        builder.forAllStates(blockState -> {
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/BlockStateProvider.java
> +    private void configureGridVariants(final DyeColor color, final Supplier<? extends Block> controller) {
```suggestion
    private void configureGridVariants(final DyeColor color, final Supplier<? extends Block> block) {
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/BlockStateProvider.java
> +    private void configureControllerVariants(final DyeColor color, final Supplier<? extends Block> controller) {
```suggestion
    private void configureControllerVariants(final DyeColor color, final Supplier<? extends Block> block) {
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/ColorHelper.java
> +public class ColorHelper {
```suggestion
public final class ColorHelper {
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/ColorHelper.java
> +    private ColorHelper() { }
```suggestion
    private ColorHelper() {
    }
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/DataGenerators.java
> +    private DataGenerators() { }
```suggestion
    private DataGenerators() {
    }
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/ItemModelProvider.java
> +        final ColorMap<?> cables = Blocks.INSTANCE.getCable();
Why remove the typing here?
```suggestion
        final ColorMap<CableBlock> cables = Blocks.INSTANCE.getCable();
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/ItemModelProvider.java
> +            createIdentifier("block/cable/" + color.getName())));
```suggestion
        cables.forEach((color, cable) -> singleTexture(
            cables.getId(color, createIdentifier("cable")).getPath(),
            base,
            "cable",
            createIdentifier("block/cable/" + color.getName())
        ));
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/ItemModelProvider.java
> +        final BlockColorMap<?> creativeControllers = Blocks.INSTANCE.getCreativeController();
Fix the generic.

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/ItemModelProvider.java
> +        final ColorMap<?> controllers = Blocks.INSTANCE.getController();
Fix the generic.

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/ItemModelProvider.java
> +        final BlockColorMap<?> grids = Blocks.INSTANCE.getGrid();
Fix the generic.

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/ItemModelProvider.java
> +        );
```suggestion
        creativeControllers.forEach((color, controller) -> withExistingParent(
            creativeControllers.getId(color, createIdentifier("creative_controller")).getPath(),
            createIdentifier("block/controller/" + color.getName())
        ));
```

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/ItemModelProvider.java
> +        );
Also try doing this in the other places.

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/recipe/RecoloringRecipeProvider.java
> +                .requires(ColorHelper.getDyeItem(color))
If the color helper is only used here, just make `getDyeItem` part of this class.

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/tag/BlockTagsProvider.java
> +public class BlockTagsProvider extends net.minecraft.data.tags.TagsProvider<Block> {
This doesn't appear to do anything?

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/tag/ItemTagGenerator.java
> +                .map(Items.INSTANCE::getFluidStoragePart)
That isn't correct. Storage disks should contain the disks, not the parts.

2023-02-19 09:10 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/tag/ItemTagGenerator.java
> +                    .map(Items.INSTANCE::getItemStoragePart)
That isn't correct. Storage disks should contain the disks, not the parts.

2023-02-19 09:34 UTC, bulldog98 commented on refinedstorage2-platform-common/src/generated/resources/data/refinedstorage2/advancements/recipes/misc/coloring/black_cable.json
> +  "parent": "minecraft:recipes/root",
Reason here is forge does not let you datagen a recipe if you do not have a criteria to unlock it. If you have a look at RecoloringRecipeProvider#recolorItems and remove the `unlockBy` you'll see that forge does not want to generate then.

2023-02-19 09:35 UTC, bulldog98 commented on refinedstorage2-platform-common/src/generated/resources/data/refinedstorage2/tags/items/fluid_storage_disks.json
> +    "refinedstorage2:64b_fluid_storage_part",
good spot.

2023-02-19 09:47 UTC, bulldog98 commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/tag/BlockTagsProvider.java
> +public class BlockTagsProvider extends net.minecraft.data.tags.TagsProvider<Block> {
Ah you need some BlockTagProvider to pass into the ItemTagProvider, since the constructor of it requires that.

2023-02-19 09:48 UTC, bulldog98 commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/tag/ItemTagGenerator.java
> +                .map(Items.INSTANCE::getFluidStoragePart)
that's the reason that the wrong thing is in the tag json.

2023-02-19 09:51 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/tag/BlockTagsProvider.java
> +public class BlockTagsProvider extends net.minecraft.data.tags.TagsProvider<Block> {
Ah ok.

2023-02-19 10:49 UTC, raoulvdberge requested changes

2023-02-19 10:49 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/block/CableBlockSupport.java
> -    private static final BooleanProperty DOWN = BooleanProperty.create("down");
Can you move these constants back to CableBlockSupport and make them public?

CableBlockSupport is reused by other cable blocks so it makes sense that they reside in here.

2023-02-19 10:49 UTC, raoulvdberge commented on refinedstorage2-platform-forge/build.gradle
> +            args '--mod', 'refinedstorage2', '--all', '--output', file('../refinedstorage2-platform-common/src/generated/resources/'), "--existing", file("../refinedstorage2-platform-common/src/main/
```suggestion
            args '--mod', 'refinedstorage2', '--all', '--output', file('../refinedstorage2-platform-common/src/generated/resources/'), "--existing", file("../refinedstorage2-platform-common/src/main/resources")
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Data'
```

2023-02-19 10:49 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/recipe/RecoloringRecipeProvider.java
> +                .requires(RecoloringRecipeProvider.getDyeItem(color))
```suggestion
                .requires(getDyeItem(color))
```

2023-02-19 10:49 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/tag/ItemTagGenerator.java
> +    public static TagKey<Item> createTag(final String name) {
Why is this public or static?

2023-02-19 10:49 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/tag/BlockTagsProvider.java
> +
add a clarifying comment why it's empty.

2023-02-19 14:06 UTC, bulldog98 commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/datagen/tag/ItemTagGenerator.java
> +    public static TagKey<Item> createTag(final String name) {
It's static, because the constants on top of that file need it, private is reasonable.

2023-02-19 15:10 UTC, raoulvdberge approved these changes

2023-02-19 15:10 UTC, merged