feat: add colored cable like items
refinedmods/refinedstorage2 pull request #336
Opened 2023-02-19 18:03 UTC by bulldog98

closes: #320

2023-02-19 20:45 UTC, raoulvdberge requested changes

2023-02-19 20:45 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/content/Items.java
> +    public void addExporters(final Supplier<NamedBlockItem> supplier) {
```suggestion
    public void addExporter(final Supplier<NamedBlockItem> supplier) {
```

2023-02-19 20:45 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/resources/assets/refinedstorage2/models/item/exporter/base.json
>    "parent": "block/block",
There's no need to put `exporter.json` under a "base" folder. After all, this model file isn't used as a "base" anywhere for other model files. It's just included in the multipart definition.

2023-02-19 20:45 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/item/block/CableBlockItem.java
> +public class CableBlockItem extends NamedBlockItem {
`CableBlockItem` can be removed I think?

2023-02-19 20:45 UTC, raoulvdberge commented on refinedstorage2-platform-fabric/src/main/java/com/refinedmods/refinedstorage2/platform/fabric/ClientModInitializerImpl.java
> +        );
```suggestion
        Blocks.INSTANCE.getExporter().values().forEach(
            block -> BlockRenderLayerMap.INSTANCE.putBlock(block, RenderType.cutout())
        );
```

2023-02-19 20:46 UTC, raoulvdberge commented
To fix the ordering issues in the datagen I think that `PROPERTY_BY_DIRECTION` needs to be ordered.

2023-02-22 19:17 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/resources/assets/refinedstorage2/models/item/exporter/base.json
>    "parent": "block/block",
Under what name and folder do you suggest to put it? Also that was to keep it in the same vain as the cable/base.json for items.

2023-02-22 19:56 UTC, bulldog98 commented
Do we want the window that is opened on exporter click to also say e.g Cyan Exporter instead of Exporter?

2023-02-22 20:49 UTC, bulldog98 commented
> To fix the ordering issues in the datagen I think that `PROPERTY_BY_DIRECTION` needs to be ordered.

Yes I had a read at `Map.of` and the implementing `ImmutableMap`  uses a random access order, that is only garantieed to be stable inside one jvm lifetime.

2023-02-23 19:29 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/resources/assets/refinedstorage2/models/item/exporter/base.json
>    "parent": "block/block",
Nvm, this is fine!

2023-02-25 12:56 UTC, raoulvdberge approved these changes

2023-02-25 12:56 UTC, merged