feat: add collapsable entries support for rei
refinedmods/refinedstorage2 pull request #340
Opened 2023-02-26 09:36 UTC by bulldog98

closes: #270

2023-02-26 13:15 UTC, raoulvdberge requested changes

2023-02-26 13:15 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/content/ColorMap.java
> +    private record ColoredSorter<T>(DyeColor color) implements Comparator<Map.Entry<DyeColor, T>> {
```suggestion
    private record ColoredSorter<T>(DyeColor defaultColor) implements Comparator<Map.Entry<DyeColor, T>> {
```

2023-02-26 13:15 UTC, raoulvdberge commented on refinedstorage2-platform-fabric/src/main/java/com/refinedmods/refinedstorage2/platform/fabric/integration/recipemod/rei/RefinedStorageREIClientPlugin.java
> +            createIdentifier("creative_controller"), Tags.CREATIVE_CONTROLLERS);
Use the constants defined in `ContentIds` instead of calling `createIdentifier` everytime.

2023-02-26 13:15 UTC, raoulvdberge commented on refinedstorage2-platform-fabric/src/main/java/com/refinedmods/refinedstorage2/platform/fabric/integration/recipemod/rei/RefinedStorageREIClientPlugin.java
> +        final DyeColor defaultColor, final ResourceLocation itemIdentifier,
```suggestion
        final DyeColor defaultColor,
        final ResourceLocation itemIdentifier,
```

2023-02-26 13:15 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/tags/Tags.java
> +package com.refinedmods.refinedstorage2.platform.common.tags;
No need for a new package, this can belong under `common.content`

2023-02-26 13:15 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/integration/recipemod/rei/RefinedStorageREIClientPlugin.java
> +            createIdentifier("creative_controller"), Tags.CREATIVE_CONTROLLERS);
Use `ContentIds`

2023-02-26 13:15 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/integration/recipemod/rei/RefinedStorageREIClientPlugin.java
> +        final DyeColor defaultColor, final ResourceLocation itemIdentifier,
```suggestion
        final DyeColor defaultColor,
        final ResourceLocation itemIdentifier,
```

2023-02-26 13:15 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/tags/Tags.java
> +    private Tags() { }
```suggestion
    private Tags() {
    }
```

2023-02-26 13:15 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/tags/Tags.java
> +public class Tags {
```suggestion
public final class Tags {
```

(convention of the content classes)

2023-02-26 13:43 UTC, bulldog98 commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/integration/recipemod/rei/RefinedStorageREIClientPlugin.java
> +            createIdentifier("creative_controller"), Tags.CREATIVE_CONTROLLERS);
did not know we had them

2023-02-26 13:46 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/tags/Tags.java
> +package com.refinedmods.refinedstorage2.platform.common.tags;
Yeah makes more sense anyway, did not think of that.

2023-02-26 13:47 UTC, bulldog98 commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/tags/Tags.java
> +    private Tags() { }
do you just prefer the constructor to have a normal scope or why do we want this?

2023-02-26 15:15 UTC, raoulvdberge commented on refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/tags/Tags.java
> +    private Tags() { }
No the private constructor is good, just the brace placement is wrong.

We want this because it can't be possible to instantiate this class since it just contains static members.

2023-02-26 17:09 UTC, raoulvdberge requested changes

2023-02-26 17:09 UTC, raoulvdberge commented on refinedstorage2-platform-fabric/src/main/java/com/refinedmods/refinedstorage2/platform/fabric/integration/recipemod/rei/RefinedStorageREIClientPlugin.java
> +            ContentIds.CREATIVE_CONTROLLER, Tags.CREATIVE_CONTROLLERS);
Passing DyeColor here again is duplicate information and can get out of sync.

I'd provide a `getDefaultBlockName()` method in `BlockColorMap`

2023-02-26 17:09 UTC, raoulvdberge commented on refinedstorage2-platform-forge/src/main/java/com/refinedmods/refinedstorage2/platform/forge/integration/recipemod/rei/RefinedStorageREIClientPlugin.java
> +            ContentIds.CREATIVE_CONTROLLER, Tags.CREATIVE_CONTROLLERS);
Passing DyeColor here again is duplicate information and can get out of sync.

I'd provide a `getDefaultBlockName()` method in `BlockColorMap`

2023-02-26 18:11 UTC, bulldog98 commented on refinedstorage2-platform-fabric/src/main/java/com/refinedmods/refinedstorage2/platform/fabric/integration/recipemod/rei/RefinedStorageREIClientPlugin.java
> +            ContentIds.CREATIVE_CONTROLLER, Tags.CREATIVE_CONTROLLERS);
Is not even needed, you can get the default and get it's name.

2023-02-27 12:46 UTC, raoulvdberge approved these changes

2023-02-27 12:47 UTC, merged