Stack upgrade gametests
refinedmods/refinedstorage2 pull request #615
Opened 2024-07-12 07:34 UTC by starforcraft

Gametests https://github.com/refinedmods/refinedstorage2/issues/248
Stack Upgrade https://github.com/refinedmods/refinedstorage2/issues/69

2024-07-12 09:24 UTC, raoulvdberge requested changes

2024-07-12 09:24 UTC, raoulvdberge commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/GameTestUtil.java
> +                if (inContainer.getItem() != net.minecraft.world.item.Items.AIR) {
I don't think full qualified is needed here since we have `RSITEMS`?

2024-07-12 09:24 UTC, raoulvdberge commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/exporter/ExporterTest.java
> +    public static void shouldExportItemStack(final GameTestHelper helper) {
```suggestion
    public static void shouldExportItemWithStackUpgrade(final GameTestHelper helper) {
```

2024-07-12 09:24 UTC, raoulvdberge commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/importer/ImporterTest.java
> +    public static void shouldImportItemStack(final GameTestHelper helper) {
```suggestion
    public static void shouldImportItemWithStackUpgrade(final GameTestHelper helper) {
```

2024-07-12 09:25 UTC, raoulvdberge commented
Can you add additional test for the constructor in item dropping mode w/ stack upgrade?

(You can see the usages of the upgrades in `AbstractModInitializer#registerUpgradeMappings`)

2024-07-12 09:41 UTC, starforcraft commented
Oh right I completely forgot that the constructor accepts stack upgrades too

2024-07-17 13:40 UTC, raoulvdberge requested changes

2024-07-17 13:40 UTC, raoulvdberge commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/GameTestUtil.java
> +                    isEmpty = false;
Just throw the exception here maybe?

2024-07-17 13:40 UTC, raoulvdberge commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/GameTestUtil.java
> +    public static void assertItemEntityPresentExactly(final GameTestHelper helper,
Why can't we use `assertItemEntityPresent` in `GameTestHelper`?

2024-07-17 13:40 UTC, raoulvdberge commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/GameTestUtil.java
> +    public static Runnable interfaceContainsExactly(final GameTestHelper helper,
Generify this so it works for every `ResourceContainer`

2024-07-17 13:40 UTC, raoulvdberge commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/GameTestUtil.java
> +    public static Runnable assertInterfaceEmpty(final GameTestHelper helper,
Generify this so it works for every `ResourceContainer`

2024-07-17 13:48 UTC, starforcraft commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/GameTestUtil.java
> +    public static void assertItemEntityPresentExactly(final GameTestHelper helper,
Because `assertItemEntityPresent ` doesn't check the number of items in one item entity

2024-07-17 14:06 UTC, raoulvdberge commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/GameTestUtil.java
> +    public static void assertItemEntityPresentExactly(final GameTestHelper helper,
Could you also use these then for the constructor gametest (drop items)

2024-07-17 14:07 UTC, raoulvdberge commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/GameTestUtil.java
> +    public static void assertItemEntityPresentExactly(final GameTestHelper helper,
for shouldDropItem -> without stack upgrade

2024-07-17 14:11 UTC, starforcraft commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/GameTestUtil.java
> +    public static Runnable assertInterfaceEmpty(final GameTestHelper helper,
How? `InterfaceBlockEntity` doesn't extend `ResourceContainer` or `ExportedResourcesContainer`

2024-07-17 14:11 UTC, starforcraft commented on refinedstorage-platform-neoforge/src/test/java/com/refinedmods/refinedstorage/platform/common/GameTestUtil.java
> +    public static Runnable interfaceContainsExactly(final GameTestHelper helper,
Same as above (or down)

2024-07-18 06:55 UTC, raoulvdberge approved these changes

2024-07-18 06:55 UTC, merged

2024-07-18 06:55 UTC, raoulvdberge commented
Thx!