fix: can't take out fluids in grid if dragging an empty fluid container
refinedmods/refinedstorage2 pull request #620
Opened 2024-07-13 13:45 UTC by starforcraft

Fixes https://github.com/refinedmods/refinedstorage2/issues/617

While trying to figure out how Github works in IntelliJ (I always use Github Desktop) I accidentally fucked up, so here is a new PR lol

2024-07-13 20:14 UTC, raoulvdberge requested changes

2024-07-13 20:14 UTC, raoulvdberge commented on CHANGELOG.md
> +-   Fixed not being able to extract fluids from the grid while dragging an empty bucket or other empty fluid container.
"from the Grid"

2024-07-13 20:14 UTC, raoulvdberge commented on refinedstorage-platform-common/src/main/java/com/refinedmods/refinedstorage/platform/common/grid/screen/AbstractGridScreen.java
> -        if (resource != null && carriedStack.isEmpty()) {
This change has the consequence that you can't click in items when you're hovering over other items. If your storage network is sufficiently full, this is very annoying.

2024-07-13 20:14 UTC, raoulvdberge commented on refinedstorage-platform-common/src/main/java/com/refinedmods/refinedstorage/platform/common/grid/view/FluidGridResource.java
> +        return Platform.INSTANCE.getFilledFluidContainer(fluidResource, container).map(fluidContainer ->
Rename "fluidContainer" to "filled"

2024-07-13 20:14 UTC, raoulvdberge commented on refinedstorage-platform-neoforge/src/main/java/com/refinedmods/refinedstorage/platform/neoforge/PlatformImpl.java
> +        ItemStack toRenderItem = container.copy();
to render item? This name makes no sense.

2024-07-13 20:14 UTC, raoulvdberge commented on refinedstorage-platform-common/src/main/java/com/refinedmods/refinedstorage/platform/common/Platform.java
> +    Optional<ItemStack> getFilledFluidContainer(FluidResource fluidResource, ItemStack container);
I'd prefer if there were 2 variants of this method. Passing  `ItemStack.EMPTY` does not make it very clear to the caller what is going to happen

2024-07-14 06:49 UTC, starforcraft commented on refinedstorage-platform-common/src/main/java/com/refinedmods/refinedstorage/platform/common/grid/screen/AbstractGridScreen.java
> -        if (resource != null && carriedStack.isEmpty()) {
Oh yeah that's right, I completely forgot about that. I thought of two possible solutions. Either I do it like this:
`if (resource != null && (resource instanceof FluidGridResource || carriedStack.isEmpty())) {
     mouseClickedInGrid(clickedButton, resource);
     return true;
}`

But then if you have for example milk in your fluid container and hover over water nothing will happen when you left click. So should I instead add a new method that checks if the carriedStack accepts the hovered FluidGridResource?

2024-07-14 09:53 UTC, raoulvdberge commented on refinedstorage-platform-common/src/main/java/com/refinedmods/refinedstorage/platform/common/grid/screen/AbstractGridScreen.java
> -        if (resource != null && carriedStack.isEmpty()) {
>  So should I instead add a new method that checks if the carriedStack accepts the hovered FluidGridResource?

Yes, but more generic so it will also work for gas tanks in the future.

2024-07-14 15:13 UTC, closed without merging