External Storage gametests
refinedmods/refinedstorage2 pull request #640
Opened 2024-08-03 08:40 UTC by starforcraft

Gametests https://github.com/refinedmods/refinedstorage2/issues/248
External Storage https://github.com/refinedmods/refinedstorage2/issues/75

2024-08-11 10:53 UTC, raoulvdberge requested changes
I'm still missing a few cases:
- changing of block state should remove from storage (e.g. removing chest block)
- changing of activeness should remove from storage
- extractions through RS seem untested?
- fuzzy mode untested
- priority untested (in combination with other RS storages)
- filter mode -> blocklist?
- access mode untested
- void excess mode
- should detect changes done to the storage itself, without interacting with RS
  - insertion of a new resource
  - addition of an existing resource
  - partial extraction of a resource
  - complete extraction of a resource
  - .. all these types of changes should reflect correctly in RS (see cache impl in `ExternalStorage`)

2024-08-11 10:53 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageTest.java
> +    public static void shouldStoreItemAllowlist(final GameTestHelper helper) {
```suggestion
    public static void shouldInsertItemAllowlist(final GameTestHelper helper) {
```

2024-08-11 10:53 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageTest.java
> +    public static void shouldStoreFluidAllowlist(final GameTestHelper helper) {
```suggestion
    public static void shouldInsertFluidAllowlist(final GameTestHelper helper) {
```

2024-08-11 10:53 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageTest.java
> +            externalStorage.setPriority(1);
Why?

2024-08-13 09:44 UTC, starforcraft commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageTest.java
> +            externalStorage.setPriority(1);
There's an item storage block connected in the network so without setting the priority to 1 the Stone won't be inserted in the chest and will instead go into the item storage block

2024-09-01 15:18 UTC, raoulvdberge requested changes
Mostly naming ;)

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldStoreItemAllowlist(final GameTestHelper helper) {
```suggestion
    public static void shouldInsertItemAllowlist(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldStoreItemFuzzyAllowlist(final GameTestHelper helper) {
```suggestion
    public static void shouldInsertItemFuzzyAllowlist(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldStoreItemBlocklist(final GameTestHelper helper) {
```suggestion
    public static void shouldInsertItemBlocklist(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldStoreItemFuzzyBlocklist(final GameTestHelper helper) {
```suggestion
    public static void shouldInsertItemFuzzyBlocklist(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldRemoveExposedItem(final GameTestHelper helper) {
```suggestion
    public static void shouldPropagateExternalExtractions(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldPartialRemoveExposedItem(final GameTestHelper helper) {
```suggestion
    public static void shouldPropagatePartialExternalExtractions(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldRemoveBrokenExposedItem(final GameTestHelper helper) {
```suggestion
    public static void shouldNoLongerExposeItemsWhenExternalBlockIsBroken(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldChangedRedstoneModeExposeItem(final GameTestHelper helper) {
```suggestion
    public static void shouldRespectRedstoneMode(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +                ))
ok, now turn redstone on and validate (place lever or redstone block or something)

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldVoidItem(final GameTestHelper helper) {
```suggestion
    public static void shouldVoidExcess(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldNotAllowExtractingItem(final GameTestHelper helper) {
```suggestion
    public static void shouldRespectInsertAccessMode(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldNotAllowInsertingItem(final GameTestHelper helper) {
```suggestion
    public static void shouldRespectExtractAccessMode(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +
Missing test: `shouldPropagateExternalInsertions` ?

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageItemTest.java
> +    public static void shouldExposeItem(final GameTestHelper helper) {
```suggestion
    public static void shouldExposeItems(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageFluidTest.java
> +    public static void shouldStoreFluidBlocklist(final GameTestHelper helper) {
```suggestion
    public static void shouldInsertFluidBlocklist(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageFluidTest.java
> +    public static void shouldStoreFluidAllowlist(final GameTestHelper helper) {
```suggestion
    public static void shouldInsertFluidAllowlist(final GameTestHelper helper) {
```

2024-09-01 15:18 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/storage/externalstorage/ExternalStorageFluidTest.java
> +        });
What about fluid extractions?

2024-09-01 17:26 UTC, raoulvdberge approved these changes

2024-09-01 17:30 UTC, merged