Relay gametest
refinedmods/refinedstorage2 pull request #748
Opened 2024-12-11 15:48 UTC by starforcraft

Gametests https://github.com/refinedmods/refinedstorage2/issues/248
Relay https://github.com/refinedmods/refinedstorage2/issues/80

2024-12-12 17:10 UTC, raoulvdberge requested changes

2024-12-12 17:10 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/GameTestUtil.java
> +        final boolean actualActive = blockEntity.calculateActive();
`calculateActive` calculates the activeness from scratch. Why not check the actual block state?

2024-12-12 17:10 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTest.java
> +            relay.setPassThrough(true);
Maybe remove this, so that we can ensure it's in passthrough mode by default.

2024-12-12 17:10 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTest.java
> +            final BlockPos pos2 = pos.above();
Give this a descriptive name, to what is this pos referring too?

2024-12-12 17:10 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTest.java
> +            final BlockPos pos2 = pos.above();
I think it's a good idea that this pos (whatever it refers to) is part of the `GameTestPlots` lambda

2024-12-12 17:10 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTest.java
> +                .thenSucceed();
Ok, but maybe also check if the storage of the other network is empty?

2024-12-12 17:10 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTest.java
> +                .thenSucceed();
Please also check the energy storage

2024-12-12 17:10 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTest.java
> +                .thenSucceed();
Please also check the energy storage

2024-12-12 17:10 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTest.java
> +                .thenSucceed();
Please check the energy storage

2024-12-12 17:10 UTC, raoulvdberge commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTestPlots.java
> +            relayPos,
So everywhere where we do `pos2`, pass an extra position here for the second network pos, and give it a descriptive name everywhere instead of `pos2`.

2024-12-12 19:39 UTC, starforcraft commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTest.java
> +                .thenSucceed();
Well, this is also checked because if the block is active, energy must be available

2024-12-13 17:39 UTC, starforcraft commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTest.java
> +                .thenSucceed();
However on second thought it makes sense to add that extra check

2024-12-13 17:39 UTC, starforcraft commented on refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common/networking/RelayTestPlots.java
> +            relayPos,
Sure, but there's no QuadConsumer iirc
So should I pass it as a BlockPos[] instead?

2024-12-14 16:39 UTC, raoulvdberge approved these changes

2024-12-14 16:39 UTC, merged